# Generated by Django 4.0.5 on 2022-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='pics')),
                ('size', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('dis', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
