# Generated by Django 4.0.5 on 2022-06-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_comment_remove_orderitem_product_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
